[mihomo-alpha]
src.git = "https://github.com/MetaCubeX/mihomo"
src.branch = "Alpha"
fetch.github = "MetaCubeX/mihomo"

[vue-language-server]
src.git = "https://github.com/vuejs/language-tools"
fetch.url = "https://registry.npmjs.org/@vue/language-server/-/language-server-2.2.0.tgz"

[unocss-language-server]
src.git = "https://github.com/xna00/unocss-language-server"
fetch.url = "https://registry.npmjs.org/unocss-language-server/-/unocss-language-server-0.1.5.tgz"

[waydroid_script]
src.git = "https://github.com/huakim/waydroid_script"
fetch.github = "huakim/waydroid_script"
