# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  mihomo-meta = {
    pname = "mihomo-meta";
    version = "2debb953ad196b2f67e5e740da1c8dcba0cb4c0b";
    src = fetchFromGitHub {
      owner = "MetaCubeX";
      repo = "mihomo";
      rev = "2debb953ad196b2f67e5e740da1c8dcba0cb4c0b";
      fetchSubmodules = false;
      sha256 = "sha256-leeD/lra0ZA7in5ZX+uZwWRyHEaE9WzC8UEigI+Z+aA=";
    };
    date = "2025-01-02";
  };
}
