# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  mihomo-alpha = {
    pname = "mihomo-alpha";
    version = "1c5f4a3ab12ae748cf85b1f14e1841f3b570e9c3";
    src = fetchFromGitHub {
      owner = "MetaCubeX";
      repo = "mihomo";
      rev = "1c5f4a3ab12ae748cf85b1f14e1841f3b570e9c3";
      fetchSubmodules = false;
      sha256 = "sha256-leeD/lra0ZA7in5ZX+uZwWRyHEaE9WzC8UEigI+Z+aA=";
    };
    date = "2024-12-31";
  };
  vue-language-server = {
    pname = "vue-language-server";
    version = "f68dafb4e37e6ea8c0285401e67e5f2fc2623913";
    src = fetchurl {
      url = "https://registry.npmjs.org/@vue/language-server/-/language-server-2.2.0.tgz";
      sha256 = "sha256-foWKEhK8YE4ZsbejJUKKPNR+G7ZrJWIPEk/1PVe6YRo=";
    };
    date = "2025-01-04";
  };
}
